<a href="https://colab.research.google.com/github/CrisHarsche/DS_Python/blob/main/DemonstNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Demonstração NumPy
Disciplina - Introdução à Ciência de Dados - Univesp



Prof. Dr. José Eduardo Santarem Segundo


Importar biblioteca


In [1]:
import numpy as np

Gerar dados aleatórios


Gerar um NDArray de 2x3


In [2]:
dados=np.random.rand(2,3)

In [3]:
dados

array([[0.8786406 , 0.47485105, 0.96754347],
       [0.51345253, 0.8364917 , 0.18888384]])

Tipo do Array


In [4]:
dados.dtype

dtype('float64')

Tamanho e quantidade de dimensões

In [5]:
dados.shape

(2, 3)

In [6]:
dados.ndim

2

Criar ndarray usando a função array

Ao criar o array a função array tenta utilizar o melhor tipo de dado


In [7]:
lista={1,2,5,7.8,1.25}

In [8]:
dados2=np.array(lista)

In [9]:
dados2

array({1, 2, 1.25, 5, 7.8}, dtype=object)

In [10]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [11]:
dados3=np.array(lista2)

In [12]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

Outras maneiras de criar arrays

In [13]:
dadoszero=np.zeros(10)

In [14]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
dadoszero2=np.zeros((2,3))

In [17]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
dadosum=np.ones(5)

In [19]:
dadosum

array([1., 1., 1., 1., 1.])

In [20]:
dadosseq=np.arange(10)

In [21]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
dadosseq2=np.arange(0,20,2)

In [23]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
dadosseq.dtype

dtype('int64')

In [25]:
dadosseqf=dadosseq.astype(np.float64)

In [26]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
dadosseqf.dtype

dtype('float64')

Aritmética com Arrays

In [28]:
dados4=np.array([[1,2,3],[4,5,6]])

In [29]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
dados5=dados4+dados4

In [34]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [35]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

Indexação

In [37]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
dadosseq[5]

5

Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de banco de dados

Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [39]:
dadosseq[3:6]

array([3, 4, 5])

In [40]:
dadosseq[3:6]=20

In [41]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [42]:
fatiadados=dadosseq[2:4]

In [43]:
fatiadados

array([ 2, 20])

In [44]:
fatiadados[1]=2000

In [45]:
fatiadados

array([   2, 2000])

In [46]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [47]:
fatiadados[:]=333

In [48]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Copiar dados

In [49]:
fatia2=dadosseq[2:4].copy()

In [50]:
fatia2

array([333, 333])

In [51]:
fatia2[:]=111

In [52]:
fatia2

array([111, 111])

In [53]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Array com mais de uma dimensão

In [56]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
dados6[1,2]

6

Máscaras

In [59]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [60]:
mascara=(dadosseq<100)

In [61]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
dadosseq[dadosseq<20]=888

In [63]:
dadosseq

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

Transposição

In [64]:
dados7=np.arange(15).reshape((3,5))

In [65]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de matrizes com dots

In [67]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])